### ISSUE TITLE
[S1 - PBI3] User Profile

### ISSUE THREAD

**Issue by rafichann** [rafichann/SI4408-KEL266#4]

**Comment by soniafrisca2** [comment]
Saya sebagai petani dan pembeli, saya ingin melihat data diri saya di halaman profil sehingga saya dapat memastikan data diri dari petani dan pembeli
<img width="859" alt="Screen_Shot_2020-04-26_at_7 10 05_AM (1)" src="https://user-images.githubusercontent.com/115615536/227703730-4b98caa4-2297-43a0-a20d-9b694547e924.png">
