### ISSUE TITLE
[S1 - PBI5] Halaman artikel

### ISSUE THREAD

**Issue by rafichann** [rafichann/SI4408-KEL266#6]

**Comment by aisyahaydila** [comment]
Saya sebagai programmer, saya ingin membuat fitur halaman katalog pada website Kios Tani, sehingga pembeli dapat memilih produk berdasarkan katalog yang tersedia.
![images](https://user-images.githubusercontent.com/115569262/227703957-dcbfcb0c-2a49-46f5-9c04-eeb7e3257143.png)
