### ISSUE TITLE
[S1 - PBI7] Halaman katalog

### ISSUE THREAD

**Issue by rafichann** [rafichann/SI4408-KEL266#8]

**Comment by nisanabb** [comment]
Saya sebagai analyst ingin melihat halaman katalog sehingga saya dapat melihat barang2 apa sja yang dijual dikatalog kios tani.

![image](https://user-images.githubusercontent.com/115602048/227703774-e4fc5c44-751e-4f7c-860b-00cf599ff11a.png)
![image](https://user-images.githubusercontent.com/115602048/227703859-698ea6d0-0e35-483f-beb4-03c30f6d4441.png)
